### ISSUE TITLE
Unable to Insert Data into Database When Form is Submitted

### ISSUE THREAD

**Issue by AianLouise** [bscs3a/Master#36]
**Issue**
I am encountering a problem where I am unable to insert data into the database when submitting a form. Instead, upon clicking the submit button, the page redirects to either '/' or '/master'. 

**Probable Cause**
It seems like there might be an issue with the router configuration, causing unexpected redirection upon form submission.

**Steps to Reproduce**
1. Navigate to the form page.
2. Fill in the required fields.
3. Click on the submit button.

**Expected Behavior**
Upon clicking the submit button, the form data should be inserted into the database, and the page should not redirect unexpectedly.

**Actual Behavior**
After clicking the submit button, the page redirects to '/' or '/master' without inserting the data into the database.

**Comment by Rokhai** [comment]
I also did testing about this issue. I created simple Form with POST Method. Its true that the submit button had unexpected behavior in addition of Unsuccessful data insertion.

```html
<form method="POST">
  <input type="text" name="name" placeholder="Type your name...">
  <input type="submit" name="submit" value="submit">
</form>
``` 

Probable Cause: Unidentified

But in my opinion in this block of codes only serves the GET Method for an HTTP request within the server. That's why POST method can't proceed.


```php
class Router
{
    public static $validRoutes = [];

    public static function setRoutes($routes)
    {
        self::$validRoutes = $routes;
    }

    public static function handle($method = 'GET', $path = '/')
    {
        $currentMethod = $_SERVER['REQUEST_METHOD'];
        $currentUri = $_SERVER['REQUEST_URI'];

        if ($currentMethod != $method) {
            return;
        }

        // Get the base path of the application
        $basePath = dirname($_SERVER['SCRIPT_NAME']);

        // Replace the base path in the current URI
        $currentUri = str_replace($basePath, '', $currentUri);

        // If the current URI is an empty string, set it to "/"
        if ($currentUri === '') {
            $currentUri = '/';
        }

        $validRoutes = self::$validRoutes;

        if (array_key_exists($currentUri, $validRoutes)) {
            require_once $validRoutes[$currentUri];
        } else {
            // The route is not valid
            require_once __DIR__ . "/src/error.php";
        }

        exit();
    }
}
``` 

Suggestion
- Create A Handler for POST Request Method 
- If the purpose of this router solely for routing of pages,, utilize the existing header function of PHP with alike of router concept

PS: i did try creating POST request handler,  but I don't have strong foundation of MVC routing like Laravel to fix this issue


@bscs3a/group-1
@bscs3a/group-2  
@bscs3a/group-3
@bscs3a/group-4 
@bscs3a/group-5 
@bscs3a/group-6



pa check nalng din

**Comment by AriesJ12** [comment]
bat kayo nag eenglish; gagi

dumudugo utak ko

**Comment by AriesJ12** [comment]
alisin na natin ng buo ung router?

another possible fix tho is to utilize js ajax functions; pero baka maging too complicated na sa iba.

**Comment by warmybruh** [comment]
I made a new branch `post-method` on the `master` repo and I'm not sure if this is a possible fix since I haven't tried it on database yet it works stroring data on session

**Comment by AriesJ12** [comment]
future problem with the current solution is function declaration:
![image](https://github.com/bscs3a/Master/assets/119474970/2fb9f407-1b41-4faa-9a63-b41f0d5bf19a)

![image](https://github.com/bscs3a/Master/assets/119474970/d190eda3-553a-44e4-ac0f-69b8bd29030a)

how to reproduce:
1. create 2 seperate files (.php)
2. declare the same function(name)
3. include it in the routing(kahit saan ilagay ung 2 basta sa mga routes.php(kahit seperate subsystem))


possible solution
1. implement OOP
2. Have a standard for naming in functional programming
3. use namespace for functions(dont even know if thats possible lol)
4. hard code functions in the calling of post(totally not recommended, kasi super dami ng redundancy pag ganon)

im just moving this notion because parang palagi nalang kasi nag kakaproblem sa routing + saving of repo(extra steps pa para mag pull request) + extra headache sa function debugging(since functional programming tayo - lalo na since 6grps tayo baka more than 40 ang magawang functions) + kagrp ko si bruce, siempre mas better kung less work sakanya para more work mabigay niya samin lol


**i suggest again to remove the routing completely. its returns are low for its high work, it will only be high return if we are actually using MVC and adding security features like preventing csrf attacks**

pros of our routing:
- handling of 404 not found
- cooler xD

cons of our routing
- extra learning curve for new programmers
- extra work for the project manager
- too much issue
- extra steps needed on pull request

**Comment by warmybruh** [comment]
solved
